spring:
  application:
    name: Spring Boot Learning v3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

custom:
  jwt-access-token-expiration: 90 # In Min
  jwt-refresh-token-expiration: 1 # In Days

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    sql: debug
    web: debug
